<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1589262133287' stop='1589262143055'>
    <name>Perform Few Window Actions</name>
    <title>Perform Few Window Actions</title>
    <test-cases>
        <test-case start='1589262133291' status='broken' stop='1589262143051'>
            <name>Window Handle</name>
            <title>Window Handle</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='1-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='firefox-10.0'/>
            </parameters>
            <steps>
                <step start='1589262133431' status='broken' stop='1589262143051'>
                    <name>POST /session/:sessionId/url</name>
                    <title>POST /session/:sessionId/url</title>
                    <attachments>
                        <attachment title='Request' source='080cc8c7-b688-427f-a0b6-662694e9bd31-attachment.json' type='application/json' size='48'/>
                    </attachments>
                    <steps>
                        <step start='1589262142812' status='passed' stop='1589262143047'>
                            <name>GET /session/:sessionId/screenshot</name>
                            <title>GET /session/:sessionId/screenshot</title>
                            <attachments>
                                <attachment title='Screenshot' source='eebd49e1-be39-450d-b435-c73409280e40-attachment.png' type='image/png' size='32238'/>
                            </attachments>
                            <steps/>
                        </step>
                    </steps>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//https//www.salesforce.com/&amp;c=UTF-8&amp;f=regular&amp;d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20https.</message>
                <stack-trace>unknown error: Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//https//www.salesforce.com/&amp;c=UTF-8&amp;f=regular&amp;d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20https.
                    at getErrorFromResponseBody (C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\webdriver\build\utils.js:121:10)
                    at WebDriverRequest._request (C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\webdriver\build\request.js:148:56)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)
                    at async Browser.runCommandWithHooks (C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\@wdio\sync\build\wrapCommand.js:88:21)
                    at Browser.runCommandWithHooks (C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\@wdio\sync\build\wrapCommand.js:82:22)
                    at Browser.wrapCommandFn (C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\@wdio\sync\build\wrapCommand.js:59:40)
                    at Context.&lt;anonymous> (C:\Workspace-JS\WEBIO-App-POM-Framework\test\windowActions.js:5:17)
                    at Context.executeSync (C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\@wdio\sync\build\index.js:56:18)
                    at C:\Workspace-JS\WEBIO-App-POM-Framework\node_modules\@wdio\sync\build\index.js:82:70</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>